/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ma.emsi.tpcustomerapplicationmelhaouitarek.session;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.Resource;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import ma.emsi.tpcustomerapplicationmelhaouitarek.entities.Customer;

/**
 *
 * @author Xune (autogenerated default user for MelhaouiTarek)
 */
@Stateless
public class CustomerManager {

    @PersistenceContext(unitName = "customerPU")
    private EntityManager em;
    @Resource
    private javax.transaction.UserTransaction utx;

     public List<Customer> getAllCustomers() {  
         Query query = em.createNamedQuery("Customer.findAll");
      return query.getResultList();  
    }  
        
    public Customer update(Customer customer) {
      return em.merge(customer);
    }  

    public void persist(Customer customer) {
        try {
            utx.begin();
            em.persist(customer);
            utx.commit();
        } catch (Exception e) {
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, "exception caught", e);
            throw new RuntimeException(e);
        }
    }
}
